import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
const visit=async path=>{await page.goto(`http://127.0.0.1:${process.env.PORT||3100}${path}`,{waitUntil:'networkidle'});};
const test=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
try {
  await visit('/san-pham');
  await test('Desktop dropdown and active menu',async()=>{await page.locator('.menu > ul > li').first().hover();assert(await page.locator('.menu > ul > li > ul').first().isVisible());assert.equal(await page.locator('.menu > ul > li > a.active').innerText(),'Mua xe');});
  await test('Header utility dropdown and direct links',async()=>{assert.equal(await page.locator('.menu > ul > li > a[title="Giới thiệu"]').getAttribute('href'),'/ve-chung-toi');assert.equal(await page.locator('.menu > ul > li > a[title="Tuyển dụng"]').getAttribute('href'),'/he-thong-oto-toan-trung-tuyen-dung');assert.equal(await page.locator('.menu > ul > li > ul').count(),4);const tabs=await page.locator('.menu > ul > li > a').allTextContents();assert.deepEqual(tabs.slice(3,5),['Tin tức','Tiện ích']);const plain=page.locator('.menu > ul > li > a[title="Tin tức"]'),dropdown=page.locator('.menu > ul > li > a[title="Tiện ích"]');assert.equal(await plain.evaluate(el=>getComputedStyle(el).backgroundImage),'none');assert.equal(await plain.evaluate(el=>getComputedStyle(el,'::after').content),'none');assert.notEqual(await dropdown.evaluate(el=>getComputedStyle(el,'::after').content),'none');await dropdown.hover();const utilities=page.locator('.menu > ul > li:has(> a[title="Tiện ích"]) > ul > li > span');assert(await utilities.first().isVisible());assert.deepEqual(await utilities.allTextContents(),['Định giá xe','Tra cứu phạt nguội','Xem ngày mua xe','Xem giá xăng dầu']);assert.equal(await page.locator('.wap_header .fine-lookup').count(),0);assert.equal(await page.locator('.wap_header .user_login').count(),0);});
  await test('Car-card left arrow points left and moves to previous image',async()=>{const card=page.locator('.wap_item > .item').first(),slider=card.locator('.slick_hinhthem');assert((await slider.locator('.slick-slide:not(.slick-cloned)').count())>1);const prev=slider.locator('.slick-prev'),next=slider.locator('.slick-next');assert((await prev.evaluate(el=>new DOMMatrixReadOnly(getComputedStyle(el).transform).a))<0);assert((await next.evaluate(el=>new DOMMatrixReadOnly(getComputedStyle(el).transform).a))>0);const first=await slider.locator('.slick-current img').getAttribute('src');await prev.click();await page.waitForTimeout(1100);assert.notEqual(await slider.locator('.slick-current img').getAttribute('src'),first);await next.click();await page.waitForTimeout(1100);assert.equal(await slider.locator('.slick-current img').getAttribute('src'),first);});
  await test('Contact popup, source styles, Escape and repeated opening',async()=>{for(let i=0;i<2;i++){await page.locator('.btn-phone').click();const modal=page.locator('.migrated-dialog #nutgoi');await modal.waitFor({state:'visible'});assert((await modal.locator('a[href^="tel:"]').count())>10);assert((await modal.boundingBox()).width<=500);await page.keyboard.press('Escape');assert.equal(await page.locator('[role=dialog]').count(),0);}});
  await test('Filter tabs, range keyboard and reset',async()=>{await page.locator('.chonloc li[data-id=".ngansach_tk"]').click();assert(await page.locator('.ngansach_tk').isVisible());const handle=page.locator('#ngansach-range [role=slider]').first();const before=Number(await handle.getAttribute('aria-valuenow'));await handle.focus();await page.keyboard.press('ArrowRight');assert.equal(Number(await handle.getAttribute('aria-valuenow')),before+10);await page.locator('.lammoi').click();assert.equal(Number(await handle.getAttribute('aria-valuenow')),before);await page.keyboard.press('Escape');assert(!(await page.locator('.wap_boloc').getAttribute('class')).includes('wap_boloc_active'));});
  await test('Compare two captured cars and remove',async()=>{await page.locator('.c_sosanh').click();await page.locator('.wap_item > .item .id_ss').nth(0).click();await page.locator('.wap_sosanhxe .td').click();await page.locator('.wap_item > .item .id_ss').nth(1).click();assert.equal(await page.locator('.sosanhxe2 .item_ss').count(),2);await page.locator('.xoa_ss').first().click();assert.equal(await page.locator('.sosanhxe2 .item_ss').count(),1);await page.locator('.c_sosanh').click();});
  await test('Keyword search uses captured inventory',async()=>{await page.locator('#keyword').fill('Honda BRV');await page.locator('#keyword').press('Enter');await page.waitForURL('**/san-pham?keyword=*');await page.waitForLoadState('networkidle');const names=await page.locator('.wap_item .name_sp').allTextContents();assert(names.length>0);assert(names.every(name=>name.toLowerCase().includes('honda brv')));});
  await visit('/toyota-fortuner-dau-at-2022');
  await test('Gallery thumbnail, full image dialog and keyboard navigation',async()=>{await page.locator('.album_pro2 .slick-slide[data-index="1"]').click();await page.waitForTimeout(700);assert.equal(await page.locator('.album_pro .slick-current').getAttribute('data-index'),'1');await page.locator('.album_pro .slick-current a').click();await page.locator('.dialog-image').waitFor({state:'visible'});const src=await page.locator('.dialog-image').getAttribute('src');await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('.dialog-image').getAttribute('src'),src);await page.keyboard.press('Escape');});
  await test('Form select arrows stay inset on all form types',async()=>{for(const route of ['/','/ban-xe','/len-doi','/toyota-fortuner-dau-at-2022']){await visit(route);const selects=page.locator('select.form-control:visible');assert((await selects.count())>0,`No visible selects on ${route}`);const styles=await selects.evaluateAll(elements=>elements.map(el=>{const style=getComputedStyle(el);return {appearance:style.appearance,position:style.backgroundPositionX,padding:parseFloat(style.paddingRight),image:style.backgroundImage};}));assert(styles.every(style=>style.appearance==='none'&&style.position.includes('16px')&&style.padding>=40&&style.image.includes('svg')),`Select arrow placement failed on ${route}`);}});
  await visit('/');
  await test('Home sell-service tab shows the four original steps',async()=>{const sellTab=page.locator('.wap_dichvu .cap1 [data-id="buoc-ban-xe"]');await sellTab.click();const sellPanel=page.locator('.wap_dichvu > .dichvu[data-service="buoc-ban-xe"]');assert(await sellPanel.isVisible());assert.equal(await sellPanel.locator('.item_buoc').count(),4);assert.equal(await sellPanel.locator('.item_buoc h4').first().innerText(),'Liên hệ và thỏa thuận');assert.equal(await sellPanel.locator('.item_buoc img').first().getAttribute('alt'),'Liên hệ và thỏa thuận');assert.equal(await sellPanel.locator('.item_buoc img').first().getAttribute('src'),'/thumbs/90x90x2/upload/news/message6772748-8616.png');assert.equal(await sellPanel.locator('.xemtatca a').getAttribute('href'),'/ban-xe');assert.equal(await sellTab.getAttribute('aria-selected'),'true');await page.locator('.wap_dichvu .cap1 [data-id="buoc-mua-xe"]').click();assert(await page.locator('.wap_dichvu > .dichvu[data-service="buoc-mua-xe"]').isVisible());assert(!(await sellPanel.isVisible()));});
  await test('Footer order, company details and newsletter fallback',async()=>{const cert=page.locator('.tt-footer-news-cert'),showrooms=page.locator('.tt-footer-showrooms');assert(await cert.isVisible());assert(await showrooms.isVisible());assert(await cert.evaluate((el,next)=>Boolean(el.compareDocumentPosition(next)&Node.DOCUMENT_POSITION_FOLLOWING),await showrooms.elementHandle()));assert.equal(await page.locator('.tt-footer-badge[role="img"]').count(),1);assert((await page.locator('.tt-footer-legal').innerText()).includes('5900674378'));await page.locator('.tt-footer-news-form input').fill('test@example.com');await page.locator('.tt-footer-news-form button').click();assert(await page.locator('.tt-footer-news-notice[role="status"]').isVisible());assert.equal(await page.locator('.migrated-dialog').count(),0);});
  await page.setViewportSize({width:375,height:900});await visit('/');
  await test('Mobile drawer utility submenu, direct links and Escape',async()=>{await page.locator('.icon_menu_mobi').click();assert.equal(await page.locator('.menu_mobi_add').getAttribute('aria-hidden'),'false');await page.locator('.menu_mobi_add > ul > li > a').first().click();assert(await page.locator('.menu_mobi_add > ul > li > ul').first().isVisible());assert.equal(await page.locator('.menu_mobi_add > ul > li > a[title="Giới thiệu"]').getAttribute('href'),'/ve-chung-toi');await page.locator('.menu_mobi_add > ul > li > a[title="Tiện ích"]').click();assert(await page.locator('.menu_mobi_add > ul > li:has(> a[title="Tiện ích"]) > ul').isVisible());assert.equal(await page.locator('.menu_mobi_add > ul > li:has(> a[title="Tiện ích"]) > ul > li > span').count(),4);assert.equal(await page.locator('.menu_mobi_add .fine-lookup').count(),0);assert.equal(await page.locator('.menu_mobi .icon_login').count(),0);await page.keyboard.press('Escape');assert.equal(await page.locator('.menu_mobi_add').getAttribute('aria-hidden'),'true');});
  assert.deepEqual(errors,[]);checks.push('No uncaught browser errors');
} finally {await mkdir('artifacts',{recursive:true});await writeFile('artifacts/interaction-report.json',JSON.stringify({checks,errors},null,2));await browser.close();}
